<?php
require_once __DIR__.'/../includes/module-shell.php';moduleReady('performance_reviews',$user,'Performance reviews');$message='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verifyCsrf();$action=$_POST['action']??'';
 if($action==='create'){
  if(!$isAdmin){http_response_code(403);exit('Access denied.');}
  $employee=sanitizeInt($_POST['employee_id']??0,1);$cycle=sanitizeString($_POST['cycle']??'',120);$due=sanitizeDate($_POST['due_date']??'');$q=$db->prepare("SELECT id FROM users WHERE id=? AND role='employee' AND status='active'");$q->execute([$employee]);
  if(!$employee||!$q->fetch()||!$cycle||!$due||$due<date('Y-m-d'))$message='Choose an active employee, review cycle, and a future deadline.';
  else{$db->prepare('INSERT INTO performance_reviews(employee_id,reviewer_id,cycle,due_date) VALUES(?,?,?,?)')->execute([$employee,$user['id'],$cycle,$due]);$id=(int)$db->lastInsertId();createNotification($employee,'performance','New performance review',$cycle.' is ready for your self-assessment.','/employee/reviews.php');auditLog('review_create','performance_reviews',$id);$message='Review assigned and employee notified.';}
 }elseif($action==='self_assessment'){
  $id=sanitizeInt($_POST['id']??0,1);$assessment=sanitizeString($_POST['self_assessment']??'',5000);
  if(!$assessment)$message='Write your self-assessment before submitting.';
  else{$q=$db->prepare("UPDATE performance_reviews SET self_assessment=?,status='submitted' WHERE id=? AND employee_id=? AND status='open'");$q->execute([$assessment,$id,$user['id']]);if($q->rowCount()){$q=$db->prepare('SELECT reviewer_id FROM performance_reviews WHERE id=?');$q->execute([$id]);createNotification((int)$q->fetchColumn(),'performance','Self-assessment submitted',$user['name'].' submitted a review.','/employee/reviews.php');auditLog('review_self_assessment','performance_reviews',$id);$message='Self-assessment submitted to your reviewer.';}else{http_response_code(403);$message='This review is not open for your assessment.';}}
 }elseif($action==='complete'){
  if(!$isAdmin){http_response_code(403);exit('Access denied.');}$id=sanitizeInt($_POST['id']??0,1);$rating=sanitizeInt($_POST['rating']??0,1,5);$feedback=sanitizeString($_POST['reviewer_feedback']??'',5000);$plan=sanitizeString($_POST['development_plan']??'',5000);
  if(!$rating||!$feedback||!$plan)$message='Provide a rating, feedback and a development plan.';
  else{$q=$db->prepare("UPDATE performance_reviews SET rating=?,reviewer_feedback=?,development_plan=?,status='completed' WHERE id=? AND reviewer_id=? AND status='submitted' AND employee_id<>?");$q->execute([$rating,$feedback,$plan,$id,$user['id'],$user['id']]);if($q->rowCount()){$q=$db->prepare('SELECT employee_id FROM performance_reviews WHERE id=?');$q->execute([$id]);createNotification((int)$q->fetchColumn(),'performance','Review completed','Your feedback and development plan are available.','/employee/reviews.php');auditLog('review_complete','performance_reviews',$id);$message='Review completed and employee notified.';}else{http_response_code(403);$message='Only the assigned reviewer can complete a submitted review.';}}
 }else{http_response_code(400);$message='Invalid action.';}
}
$q=$db->prepare('SELECT r.*,u.full_name,v.full_name reviewer_name FROM performance_reviews r JOIN users u ON u.id=r.employee_id JOIN users v ON v.id=r.reviewer_id '.($isAdmin?'WHERE r.reviewer_id=? ':'WHERE r.employee_id=? ').'ORDER BY r.created_at DESC LIMIT 100');$q->execute([$user['id']]);$reviews=$q->fetchAll();moduleStart('Performance reviews',$user,$message);?>
<div style="margin-bottom:20px"><a class="btn btn-outline" href="/employee/performance.php">Personal goals</a></div>
<?php if($isAdmin):$employees=$db->query("SELECT id,full_name FROM users WHERE role='employee' AND status='active' ORDER BY full_name")->fetchAll();?><div class="card" style="margin-bottom:24px"><div class="card-header"><h3>Start a review cycle</h3></div><form method="post" class="card-body"><?php moduleToken();?><input type="hidden" name="action" value="create"><div class="module-grid"><div class="form-group"><label>Employee</label><select class="form-control" name="employee_id" required><?php foreach($employees as $employee):?><option value="<?=(int)$employee['id']?>"><?=e($employee['full_name'])?></option><?php endforeach;?></select></div><div class="form-group"><label>Review cycle</label><input name="cycle" class="form-control" maxlength="120" placeholder="Quarterly development review" required></div><div class="form-group"><label>Due date</label><input name="due_date" class="form-control" type="date" min="<?=date('Y-m-d')?>" required></div></div><button class="btn btn-primary">Assign review</button></form></div><?php endif;?>
<?php foreach($reviews as $review):?><section class="card" style="margin-bottom:24px"><div class="card-header"><h3><?=e($review['cycle'])?> · <?=e($review['full_name'])?></h3><span class="badge"><?=e($review['status'])?></span></div><div class="card-body"><p>Reviewer: <?=e($review['reviewer_name'])?> · Due <?=e($review['due_date'])?></p><?php if($review['self_assessment']):?><h4 style="margin-top:20px">Self-assessment</h4><p style="white-space:pre-wrap"><?=e($review['self_assessment'])?></p><?php endif;?>
<?php if(!$isAdmin&&$review['status']==='open'):?><form method="post" style="margin-top:20px"><?php moduleToken();?><input type="hidden" name="action" value="self_assessment"><input type="hidden" name="id" value="<?=(int)$review['id']?>"><div class="form-group"><label>Your achievements and areas for growth</label><textarea name="self_assessment" class="form-control" maxlength="5000" rows="5" required></textarea></div><button class="btn btn-primary">Submit self-assessment</button></form><?php endif;?>
<?php if($isAdmin&&$review['status']==='submitted'):?><form method="post" style="margin-top:20px"><?php moduleToken();?><input type="hidden" name="action" value="complete"><input type="hidden" name="id" value="<?=(int)$review['id']?>"><div class="form-group"><label>Rating (1 needs support, 5 exceptional)</label><select name="rating" class="form-control"><?php for($i=1;$i<=5;$i++):?><option><?=$i?></option><?php endfor;?></select></div><div class="form-group"><label>Reviewer feedback</label><textarea name="reviewer_feedback" class="form-control" maxlength="5000" rows="4" required></textarea></div><div class="form-group"><label>Development plan</label><textarea name="development_plan" class="form-control" maxlength="5000" rows="4" required></textarea></div><button class="btn btn-primary">Complete review</button></form><?php endif;?>
<?php if($review['status']==='completed'):?><div class="alert alert-success" style="margin-top:20px">Rating: <?=(int)$review['rating']?> / 5</div><h4>Reviewer feedback</h4><p style="white-space:pre-wrap"><?=e($review['reviewer_feedback'])?></p><h4 style="margin-top:20px">Development plan</h4><p style="white-space:pre-wrap"><?=e($review['development_plan'])?></p><?php endif;?></div></section><?php endforeach;?><?php if(!$reviews):?><div class="card empty-state">No reviews assigned yet. <?=$isAdmin?'Start a cycle above.':'Your assigned reviews will appear here.'?></div><?php endif;moduleEnd();
