<?php
require_once __DIR__.'/includes/module-shell.php';
moduleReady('attendance',$user,'Workspace analytics');
$requestedDays=isset($_GET['days'])?(string)$_GET['days']:'7';$days=in_array($requestedDays,['7','30'],true)?(int)$requestedDays:7;
$start=date('Y-m-d',strtotime('-'.($days-1).' days'));$end=date('Y-m-d');
$owner=$isAdmin?[]:[$user['id']];
function analyticsCount(PDO $db,string $sql,array $args=[]): int {$q=$db->prepare($sql);$q->execute($args);return (int)$q->fetchColumn();}
$projects=analyticsCount($db,'SELECT COUNT(*) FROM projects'.($isAdmin?'':' WHERE employee_id=?'),$owner);
$pending=analyticsCount($db,"SELECT COUNT(*) FROM leave_requests WHERE status='pending'".($isAdmin?'':' AND user_id=?'),$owner);
$tasks=tableExists('project_tasks')?analyticsCount($db,"SELECT COUNT(*) FROM project_tasks t JOIN projects p ON p.id=t.project_id WHERE t.state<>'done'".($isAdmin?'':' AND p.employee_id=?'),$owner):0;
if($isAdmin){$firstLabel='Active employees';$firstValue=analyticsCount($db,"SELECT COUNT(*) FROM users WHERE role='employee' AND status='active'");$q=$db->prepare("SELECT a.work_date,COUNT(*) value FROM attendance a JOIN users u ON u.id=a.user_id WHERE a.work_date BETWEEN ? AND ? AND u.role='employee' AND u.status='active' GROUP BY a.work_date");$q->execute([$start,$end]);$distribution=$db->query("SELECT COALESCE(NULLIF(w.department,''),'General') label,COUNT(*) value FROM users u LEFT JOIN workspace_people w ON w.user_id=u.id WHERE u.role='employee' AND u.status='active' GROUP BY label ORDER BY value DESC,label")->fetchAll();$barTitle='Employee attendance';$barUnit='check-ins';$pieTitle='Team by department';}else{$firstLabel='Goals in progress';$firstValue=analyticsCount($db,'SELECT COUNT(*) FROM performance_goals WHERE user_id=? AND progress<100',[$user['id']]);$q=$db->prepare('SELECT work_date,ROUND(SUM(COALESCE(GREATEST(0,TIMESTAMPDIFF(SECOND,clock_in,clock_out))/3600,0)),2) value FROM attendance WHERE work_date BETWEEN ? AND ? AND user_id=? GROUP BY work_date');$q->execute([$start,$end,$user['id']]);$distribution=[];if(tableExists('project_tasks')){$t=$db->prepare('SELECT t.state label,COUNT(*) value FROM project_tasks t JOIN projects p ON p.id=t.project_id WHERE p.employee_id=? GROUP BY t.state');$t->execute([$user['id']]);$distribution=$t->fetchAll();}$names=['todo'=>'To do','in_progress'=>'In progress','done'=>'Completed'];foreach($distribution as &$item)$item['label']=$names[$item['label']]??$item['label'];unset($item);$barTitle='Your working hours';$barUnit='hours';$pieTitle='Your project task status';}
$records=$q->fetchAll(PDO::FETCH_KEY_PAIR);$daily=[];for($i=0;$i<$days;$i++){$date=date('Y-m-d',strtotime("$start +$i days"));$daily[$date]=(float)($records[$date]??0);}$max=max(array_merge([1],array_values($daily)));$sum=array_sum($daily);$total=array_sum(array_column($distribution,'value'));$palette=['#4b8ee8','#51bfa7','#efb26f','#a387dc','#e78fa7','#72bdce'];$stops=[];$offset=0;foreach($distribution as $i=>$item){$next=$offset+100*$item['value']/max(1,$total);$stops[]=$palette[$i%count($palette)].' '.$offset.'% '.$next.'%';$offset=$next;}
moduleStart('Workspace analytics',$user);?>
<link rel="stylesheet" href="/assets/css/analytics.css?v=<?=filemtime(__DIR__.'/assets/css/analytics.css')?>">
<section class="analytics-heading"><div><h2>A clearer view of your work.</h2><p><?=$isAdmin?'Team attendance and department distribution.':'Your attendance and project progress.'?> Data comes from your workspace database.</p></div><form method="get"><label for="analytics-range">Attendance period</label><select id="analytics-range" name="days"><option value="7" <?=$days===7?'selected':''?>>Last 7 days</option><option value="30" <?=$days===30?'selected':''?>>Last 30 days</option></select><button class="btn btn-primary" type="submit">Apply</button></form></section>
<div class="analytics-metrics"><?php foreach([[$firstLabel,$firstValue],['Project assignments',$projects],['Open project tasks',$tasks],['Pending leave requests',$pending]] as [$label,$value]):?><article class="card analytics-metric"><span><?=e($label)?></span><strong><?=(int)$value?></strong></article><?php endforeach;?></div>
<div class="analytics-charts"><section class="card analytics-chart"><header><div><h3><?=e($barTitle)?></h3><p><?=e($start)?> — <?=e($end)?></p></div><span class="analytics-total"><?=e((string)round($sum,2))?> <?=e($barUnit)?></span></header><div class="analytics-bars-scroll"><div class="analytics-bars" style="--days:<?=$days?>" role="img" aria-label="<?=e($barTitle)?>"><?php foreach($daily as $date=>$value):?><div class="analytics-bar-column"><span class="analytics-bar-value"><?=e((string)round($value,1))?></span><div class="analytics-bar-track"><div class="analytics-bar" style="height:<?=100*$value/$max?>%"></div></div><span class="analytics-bar-date"><?=date($days===7?'D':'j',strtotime($date))?></span></div><?php endforeach;?></div></div><p class="analytics-note">Days without records are shown as zero.</p></section><section class="card analytics-chart"><header><div><h3><?=e($pieTitle)?></h3><p>Current workspace distribution</p></div></header><?php if($total):?><div class="analytics-pie-layout"><div class="analytics-pie" style="background:conic-gradient(<?=e(implode(',',$stops))?>)" role="img" aria-label="Chart distribution"></div><ul class="analytics-legend"><?php foreach($distribution as $i=>$item):?><li><span class="analytics-legend-dot" style="background:<?=$palette[$i%count($palette)]?>"></span><span><?=e($item['label'])?></span><strong><?=(int)$item['value']?></strong><small><?=round(100*$item['value']/$total,1)?>%</small></li><?php endforeach;?></ul></div><?php else:?><div class="analytics-empty">No records to chart yet.</div><?php endif;?><a class="btn btn-outline" href="<?=$isAdmin?'/admin/people.php':'/project-board.php'?>"><?=$isAdmin?'Explore people':'Open project board'?> ↗</a></section></div>
<?php moduleEnd();
