<?php
require_once __DIR__.'/includes/module-shell.php';moduleReady('announcements',$user,'Announcements');$message='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verifyCsrf();if(!$isAdmin){http_response_code(403);exit('Access denied.');}$action=$_POST['action']??'';
 if($action==='publish'){$title=sanitizeString($_POST['title']??'',200);$body=sanitizeString($_POST['body']??'',10000);$audience=validateEnum($_POST['audience']??'',['everyone','employees','admins']);
  if(!$title||!$body||!$audience)$message='Provide a title, message, and audience.';
  else{$db->beginTransaction();try{$db->prepare('INSERT INTO announcements(title,body,audience,author_id) VALUES(?,?,?,?)')->execute([$title,$body,$audience,$user['id']]);$id=(int)$db->lastInsertId();$filter=$audience==='employees'?" AND role='employee'":($audience==='admins'?" AND role IN ('hr_admin','super_admin')":'');foreach($db->query("SELECT id FROM users WHERE status='active'".$filter) as $recipient)createNotification((int)$recipient['id'],'announcement',$title,'A new announcement is available.','/announcements.php');auditLog('announcement_publish','announcements',$id);$db->commit();$message='Announcement published and audience notified.';}catch(Throwable $e){$db->rollBack();$message='Unable to publish this announcement.';}}
 }elseif($action==='archive'){$id=sanitizeInt($_POST['id']??0,1);$q=$db->prepare('UPDATE announcements SET is_archived=1 WHERE id=? AND is_archived=0 AND (author_id=? OR ?=1)');$q->execute([$id,$user['id'],$user['role']==='super_admin'?1:0]);if($q->rowCount()){auditLog('announcement_archive','announcements',$id);$message='Announcement archived.';}else{http_response_code(403);$message='Only the author or a super administrator can archive this announcement.';}}
 else{http_response_code(400);$message='Invalid action.';}
}
$audience=$isAdmin?'admins':'employees';$q=$db->prepare("SELECT a.*,u.full_name FROM announcements a JOIN users u ON u.id=a.author_id WHERE a.is_archived=0 AND (a.audience IN ('everyone',?) OR ?=1) ORDER BY a.published_at DESC LIMIT 100");$q->execute([$audience,$isAdmin?1:0]);$items=$q->fetchAll();moduleStart('Announcements',$user,$message);?>
<?php if($isAdmin):?><section class="card" style="margin-bottom:24px"><div class="card-header"><h3>Share an update</h3></div><form method="post" class="card-body"><?php moduleToken();?><input type="hidden" name="action" value="publish"><div class="grid-2"><div class="form-group"><label>Title</label><input class="form-control" name="title" maxlength="200" required></div><div class="form-group"><label>Audience</label><select name="audience" class="form-control"><option value="everyone">Everyone</option><option value="employees">Employees</option><option value="admins">HR and administrators</option></select></div></div><div class="form-group"><label>Message</label><textarea name="body" class="form-control" maxlength="10000" rows="5" required></textarea></div><button class="btn btn-primary">Publish announcement</button></form></section><?php endif;?>
<?php foreach($items as $item):?><article class="card" style="margin-bottom:24px"><div class="card-header"><h3><?=e($item['title'])?></h3><span class="badge"><?=e($item['audience'])?></span></div><div class="card-body"><p style="white-space:pre-wrap"><?=e($item['body'])?></p><p style="margin-top:20px;font-size:12px;color:var(--text-2)"><?=e($item['full_name'])?> · <?=e(date('M j, Y',strtotime($item['published_at'])))?></p><?php if($isAdmin&&((int)$item['author_id']===$user['id']||$user['role']==='super_admin')):?><form method="post" style="margin-top:15px"><?php moduleToken();?><input type="hidden" name="id" value="<?=(int)$item['id']?>"><button class="btn btn-outline btn-sm" name="action" value="archive">Archive announcement</button></form><?php endif;?></div></article><?php endforeach;?><?php if(!$items):?><div class="card empty-state">No updates for your audience yet.</div><?php endif;moduleEnd();
