<?php
require_once __DIR__.'/includes/module-shell.php';moduleReady('project_tasks',$user,'Project board');moduleStart('Project board',$user);
?>
<section id="project-board" data-token="<?=e(generateCsrfToken())?>">
 <div class="board-heading"><div><div class="eyebrow">Delivery / connected teams</div><h2>Good work moves forward.</h2><p><?=$isAdmin?'Manage tasks across employee project assignments.':'Your assigned projects, priorities, and next steps.'?></p></div><button class="btn btn-primary" id="new-task" type="button" disabled>＋ New task</button></div>
 <div class="board-toolbar"><label for="board-project">Project <select id="board-project"><option value="">All projects</option></select></label><label for="board-search">Find a task <input id="board-search" type="search" placeholder="Search task titles"></label><button class="btn btn-outline" id="board-refresh" type="button">Refresh</button><span id="board-summary" aria-live="polite"></span></div>
 <p id="board-message" role="status">Loading your projects…</p>
 <div class="task-board"><?php foreach(['todo'=>'To do','in_progress'=>'In progress','done'=>'Completed'] as $state=>$label):?><section class="task-column" data-state="<?=$state?>"><header><h3><?=$label?></h3><span data-count>0</span></header><div class="task-list"></div></section><?php endforeach;?></div>
 <noscript><p>Enable JavaScript to use the interactive task board. Your assignments remain available under My projects.</p></noscript>
 <dialog id="task-dialog"><form id="task-form"><div class="board-heading"><h2 id="task-dialog-title">New task</h2><button type="button" class="btn btn-outline" id="close-task" aria-label="Close task editor">×</button></div><label for="task-project">Project</label><select id="task-project" name="project_id" required></select><label for="task-title">Task title</label><input id="task-title" name="title" maxlength="200" required><div class="task-fields"><div><label for="task-state">Status</label><select id="task-state" name="state"><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Completed</option></select></div><div><label for="task-priority">Priority</label><select id="task-priority" name="priority"><option value="low">Low</option><option value="normal" selected>Normal</option><option value="high">High</option></select></div></div><label for="task-due">Due date (optional)</label><input id="task-due" name="due_date" type="date"><p id="task-error" role="alert"></p><div class="board-heading"><button type="button" class="btn btn-outline" id="delete-task" hidden>Delete task</button><button type="submit" class="btn btn-primary" id="save-task">Save task</button></div></form></dialog>
</section>
<?php pageFooter();?><script src="/assets/js/project-board.js?v=<?=filemtime(__DIR__.'/assets/js/project-board.js')?>"></script></div></main></div></body></html>
