<?php
require_once __DIR__.'/../includes/module-shell.php';if(!$isAdmin){http_response_code(403);exit('Access denied.');}moduleReady('recruitment_candidates',$user,'Recruitment pipeline');$message='';
$stages=['applied'=>'Applied','screening'=>'Screening','interview'=>'Interview','offer'=>'Offer','hired'=>'Hired','rejected'=>'Rejected'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verifyCsrf();$action=$_POST['action']??'';
 if($action==='add'){$job=sanitizeInt($_POST['job_id']??0,1);$name=sanitizeString($_POST['full_name']??'',120);$email=sanitizeEmail($_POST['email']??'');$notes=sanitizeString($_POST['notes']??'',5000);$q=$db->prepare("SELECT id FROM job_openings WHERE id=? AND status='active'");$q->execute([$job]);
  if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL)||!$job||!$q->fetch())$message='Choose an active opening and a valid candidate name and email.';
  else{try{$db->prepare('INSERT INTO recruitment_candidates(job_id,full_name,email,notes,created_by) VALUES(?,?,?,?,?)')->execute([$job,$name,$email,$notes,$user['id']]);auditLog('candidate_add','recruitment_candidates',(int)$db->lastInsertId());$message='Candidate added to the pipeline.';}catch(PDOException $e){if($e->getCode()==='23000')$message='This candidate already has an application for that opening.';else{error_log('Candidate add failed');$message='Could not add the candidate.';}}}
 }elseif($action==='update'){
  $id=sanitizeInt($_POST['id']??0,1);$stage=validateEnum($_POST['stage']??'',array_keys($stages));$notes=sanitizeString($_POST['notes']??'',5000);$raw=trim((string)($_POST['interview_at']??''));$interview=null;
  if($raw!==''){$date=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$raw);if($date&&$date->format('Y-m-d\TH:i')===$raw)$interview=$date->format('Y-m-d H:i:s');}
  if(!$id||!$stage||($raw!==''&&!$interview))$message='Choose a valid stage and interview date.';
  else{$q=$db->prepare('UPDATE recruitment_candidates SET stage=?,notes=?,interview_at=? WHERE id=?');$q->execute([$stage,$notes,$interview,$id]);if($q->rowCount()){auditLog('candidate_update','recruitment_candidates',$id,['stage'=>$stage]);$message='Candidate stage and details saved.';}else{$message='No changes were made.';}}
 }else{http_response_code(400);$message='Invalid action.';}
}
$jobs=$db->query("SELECT id,title FROM job_openings WHERE status='active' ORDER BY title")->fetchAll();$selected=sanitizeInt($_GET['job']??0,1);$q=$db->prepare('SELECT c.*,j.title FROM recruitment_candidates c JOIN job_openings j ON j.id=c.job_id '.($selected?'WHERE c.job_id=? ':'').'ORDER BY c.updated_at DESC');$q->execute($selected?[$selected]:[]);$candidates=$q->fetchAll();$counts=array_fill_keys(array_keys($stages),0);foreach($candidates as $candidate)$counts[$candidate['stage']]++;moduleStart('Recruitment pipeline',$user,$message);?>
<div style="margin-bottom:20px"><a class="btn btn-outline" href="/admin/manage_jobs.php">Manage job openings</a></div><div class="module-grid" style="margin-bottom:24px"><?php foreach($stages as $key=>$label):?><div class="card metric"><p><?=e($label)?></p><strong><?=$counts[$key]?></strong></div><?php endforeach;?></div>
<section class="card" style="margin-bottom:24px"><div class="card-header"><h3>Add a candidate</h3></div><form method="post" class="card-body"><?php moduleToken();?><input type="hidden" name="action" value="add"><div class="grid-2"><div class="form-group"><label>Job opening</label><select name="job_id" class="form-control" required><option value="">Select an active opening</option><?php foreach($jobs as $job):?><option value="<?=(int)$job['id']?>"><?=e($job['title'])?></option><?php endforeach;?></select></div><div class="form-group"><label>Candidate name</label><input name="full_name" class="form-control" maxlength="120" required></div><div class="form-group"><label>Email</label><input name="email" type="email" class="form-control" maxlength="180" required></div><div class="form-group"><label>Application notes</label><textarea name="notes" class="form-control" maxlength="5000"></textarea></div></div><button class="btn btn-primary" <?=!$jobs?'disabled':''?>>Add candidate</button></form></section>
<form method="get" class="people-toolbar"><select name="job" class="form-control" aria-label="Filter by job"><option value="">All openings</option><?php foreach($jobs as $job):?><option value="<?=(int)$job['id']?>" <?=$selected===(int)$job['id']?'selected':''?>><?=e($job['title'])?></option><?php endforeach;?></select><button class="btn btn-outline">Filter pipeline</button></form>
<div class="module-grid"><?php foreach($candidates as $candidate):?><article class="card"><div class="card-header"><h3><?=e($candidate['full_name'])?></h3><span class="badge"><?=e($stages[$candidate['stage']])?></span></div><div class="card-body"><p><?=e($candidate['title'])?></p><p style="color:var(--text-2)"><?=e($candidate['email'])?></p><form method="post" style="margin-top:20px"><?php moduleToken();?><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=(int)$candidate['id']?>"><div class="form-group"><label>Stage</label><select name="stage" class="form-control"><?php foreach($stages as $key=>$label):?><option value="<?=e($key)?>" <?=$candidate['stage']===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></div><div class="form-group"><label>Interview time (<?=e(date_default_timezone_get())?>)</label><input type="datetime-local" name="interview_at" class="form-control" value="<?=$candidate['interview_at']?e(date('Y-m-d\TH:i',strtotime($candidate['interview_at']))):''?>"></div><div class="form-group"><label>Notes</label><textarea name="notes" class="form-control" rows="3" maxlength="5000"><?=e($candidate['notes']??'')?></textarea></div><button class="btn btn-primary">Save candidate</button></form></div></article><?php endforeach;?></div><?php if(!$candidates):?><div class="card empty-state">No candidates yet. Add an application above.</div><?php endif;moduleEnd();
