<?php
require_once __DIR__.'/../includes/module-shell.php';require_once __DIR__.'/../includes/hr-operations.php';if(!$isAdmin){http_response_code(403);exit('Access denied.');}moduleReady('workspace_people',$user,'Workforce analytics');
$start=sanitizeDate($_GET['start']??'')?:date('Y-m-01');$end=sanitizeDate($_GET['end']??'')?:date('Y-m-d');$department=sanitizeString($_GET['department']??'',80);$error='';if($end<$start||strtotime($end)-strtotime($start)>366*86400){$error='Choose a date range of up to one year.';$start=date('Y-m-01');$end=date('Y-m-d');}
$sql="SELECT u.id,u.full_name,u.email,u.status,COALESCE(p.department,'General') department,COALESCE(p.job_title,'Team member') job_title,
 COALESCE(a.days,0) attendance_days,COALESCE(a.hours,0) hours_worked,COALESCE(t.hours,0) submitted_hours
 FROM users u LEFT JOIN workspace_people p ON p.user_id=u.id
 LEFT JOIN (SELECT user_id,COUNT(*) days,SUM(TIMESTAMPDIFF(SECOND,clock_in,clock_out)/3600) hours FROM attendance WHERE work_date BETWEEN ? AND ? GROUP BY user_id) a ON a.user_id=u.id
 LEFT JOIN (SELECT user_id,SUM(total_hours) hours FROM timesheets WHERE week_start BETWEEN ? AND ? AND status IN ('pending','approved') GROUP BY user_id) t ON t.user_id=u.id
 WHERE u.role='employee'";
$params=[$start,$end,$start,$end];if($department!==''){$sql.=" AND COALESCE(p.department,'General')=?";$params[]=$department;}$sql.=' ORDER BY u.full_name';$q=$db->prepare($sql);$q->execute($params);$rows=$q->fetchAll();
if(($_GET['export']??'')==='csv'&&$error===''){
 sendNoCacheHeaders();header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="workforce-report.csv"');$file=fopen('php://output','w');fputcsv($file,['Name','Email','Status','Department','Role','Attendance days','Completed work hours','Submitted timesheet hours'],',','"','');foreach($rows as $r)fputcsv($file,array_map('csvCell',[$r['full_name'],$r['email'],$r['status'],$r['department'],$r['job_title'],$r['attendance_days'],number_format((float)$r['hours_worked'],2,'.',''),$r['submitted_hours']]),',','"','');fclose($file);auditLog('workforce_export','users',null,['start'=>$start,'end'=>$end,'department'=>$department]);exit;
}
$departments=$db->query('SELECT DISTINCT department FROM workspace_people ORDER BY department')->fetchAll(PDO::FETCH_COLUMN);moduleStart('Workforce analytics',$user,$error);?>
<section class="card" style="margin-bottom:24px"><form class="card-body" method="get"><div class="module-grid"><div class="form-group"><label>From</label><input name="start" class="form-control" type="date" value="<?=e($start)?>" required></div><div class="form-group"><label>Through</label><input name="end" class="form-control" type="date" value="<?=e($end)?>" required></div><div class="form-group"><label>Department</label><select name="department" class="form-control"><option value="">All departments</option><?php foreach($departments as $d):?><option <?=$d===$department?'selected':''?>><?=e($d)?></option><?php endforeach;?></select></div></div><button class="btn btn-primary">Update report</button> <button class="btn btn-outline" name="export" value="csv">Export CSV</button></form></section>
<div class="metrics-row"><div class="card metric"><p>Employees in report</p><strong><?=count($rows)?></strong></div><div class="card metric"><p>Completed work hours</p><strong><?=number_format(array_sum(array_column($rows,'hours_worked')),1)?></strong></div><div class="card metric"><p>Submitted timesheet hours</p><strong><?=number_format(array_sum(array_column($rows,'submitted_hours')),1)?></strong></div></div><p style="margin-bottom:20px;color:var(--text-2)">Attendance uses completed clock-in/out records. Timesheets include pending and approved weeks whose start dates fall in the selected range.</p>
<section class="card"><div class="table-scroll"><table class="table"><thead><tr><th>Employee</th><th>Department</th><th>Job title</th><th>Attendance days</th><th>Work hours</th><th>Timesheet hours</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['full_name'])?><br><small><?=e($r['email'])?></small></td><td><?=e($r['department'])?></td><td><?=e($r['job_title'])?></td><td><?=(int)$r['attendance_days']?></td><td><?=number_format((float)$r['hours_worked'],1)?></td><td><?=number_format((float)$r['submitted_hours'],1)?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$rows):?><div class="empty-state">No people match these filters.</div><?php endif;?></section><?php moduleEnd();
