<?php
require_once __DIR__.'/dashboard-operations.php';
$hasPeople=tableExists('workspace_people');
$people=$db->query("SELECT u.id,u.full_name,u.start_date,u.status".($hasPeople?',p.department,p.job_title,p.avatar_color,p.is_demo':",'General' department,'Team member' job_title,'#b6a2ed' avatar_color,0 is_demo").' FROM users u '.($hasPeople?'LEFT JOIN workspace_people p ON p.user_id=u.id ':'')."WHERE u.role='employee' ORDER BY u.created_at DESC LIMIT 6")->fetchAll();
$demoCount=$hasPeople?(int)$db->query('SELECT COUNT(*) FROM workspace_people WHERE is_demo=1')->fetchColumn():0;
$departments=$hasPeople?$db->query("SELECT p.department,COUNT(*) total FROM workspace_people p JOIN users u ON u.id=p.user_id WHERE u.status='active' AND u.role='employee' GROUP BY p.department ORDER BY total DESC")->fetchAll():[];
$todayAttendance=tableExists('attendance')?(int)$db->query('SELECT COUNT(*) FROM attendance WHERE work_date=CURRENT_DATE')->fetchColumn():0;
$pendingLeave=tableExists('leave_requests')?(int)$db->query("SELECT COUNT(*) FROM leave_requests WHERE status='pending'")->fetchColumn():0;
$jobs=tableExists('job_openings')?(int)$db->query("SELECT COUNT(*) FROM job_openings WHERE status='active'")->fetchColumn():0;
$attendance=[];if(tableExists('attendance')){$attendance=$db->query('SELECT work_date,COUNT(*) total FROM attendance WHERE work_date>=DATE_SUB(CURRENT_DATE,INTERVAL 6 DAY) GROUP BY work_date')->fetchAll(PDO::FETCH_KEY_PAIR);}
$activities=$db->query('SELECT action,created_at FROM audit_log ORDER BY created_at DESC LIMIT 4')->fetchAll();
$monthDays=(int)date('t');$firstDay=(int)date('N',strtotime(date('Y-m-01')));
$colors=['#b29ad9','#e8c5a7','#bed6c8','#b9c8e6','#d9bedb','#cbd4b0'];$totalDept=array_sum(array_column($departments,'total'));$stops=[];$offset=0;foreach($departments as $i=>$department){$end=$offset+($totalDept?100*$department['total']/$totalDept:0);$stops[]=$colors[$i%6].' '.$offset.'% '.$end.'%';$offset=$end;}
pageHead('Overview'); ?>
<body><div class="app-shell"><?php renderSidebar($user,'dashboard');?><main class="main-content"><?php renderTopbar('Workspace / Overview',$user);?><div class="page-body">
<?php if($demoCount):?><div class="demo-banner"><span>DEMO WORKSPACE</span> <?= $demoCount ?> fictional profiles · sample records are for exploration</div><?php endif;?>
<div class="overview-heading"><div><h1>Welcome back, <?=e(explode(' ',$user['name'])[0])?> <span style="color:#c4b0dc">✦</span></h1><p>Here's what's happening with your people today.</p></div><a class="btn btn-primary" href="/admin/create_account.php">＋ Add team member</a></div>
<div class="overview-layout"><div class="overview-main">
<section class="overview-hero"><div class="overview-hero-copy"><div class="eyebrow">A LITTLE MORE HUMAN. A LOT MORE CONNECTED.</div><h2>Great teams start<br>with happy people.</h2><p>Bring your people, their growth, and everyday work together. A beautiful space to do your best work.</p><a class="btn btn-primary btn-sm" href="/admin/people.php">Meet your team ↗</a></div><div class="office-scene" data-office aria-label="Interactive 3D team workspace"><span class="scene-caption">YOUR PEOPLE, CONNECTED</span></div></section>
<div class="metrics-row">
<?php foreach([['Total employees',$stats['active_employees'],'◈','Active people in your workspace','/admin/people.php'],['Checked in today',$todayAttendance,'◷','Live attendance records','/employee/attendance.php'],['Pending requests',$pendingLeave,'▦','Leave requests to review','/employee/leave.php'],['Open positions',$jobs,'↗','Find your next great teammate','/admin/manage_jobs.php']] as [$label,$value,$icon,$detail,$link]):?><a class="card metric" href="<?=e($link)?>"><span class="metric-symbol"><?=e($icon)?></span><p><?=e($label)?></p><strong><?=$value?></strong><small><?=e($detail)?></small></a><?php endforeach;?></div>
<?php renderDashboardOperations($db,$user);?><div class="chart-row"><section class="card"><div class="section-head"><h3>Attendance overview</h3><span>Last 7 days ↗</span></div><div class="chart-body"><div class="attendance-chart" role="img" aria-label="Daily attendance over the last seven days"><?php $max=max(1,...array_values($attendance));for($d=6;$d>=0;$d--):$date=date('Y-m-d',strtotime("-$d days"));$count=(int)($attendance[$date]??0);?><div class="attendance-bar" title="<?=e($date)?>: <?=$count?> checked in" style="height:<?=max(3,120*$count/$max)?>px"></div><?php endfor;?></div><div class="chart-labels"><?php for($d=6;$d>=0;$d--):?><span><?=date('D',strtotime("-$d days"))?></span><?php endfor;?></div></div></section>
<section class="card"><div class="section-head"><h3>Team distribution</h3><a href="/admin/people.php">View team ↗</a></div><div class="chart-body donut-wrap"><div class="donut" style="background:conic-gradient(<?=e(implode(',',$stops)?:'#eee7f5 0% 100%')?>)" role="img" aria-label="<?=$totalDept?> team members across departments"><strong><?=$totalDept?><small style="display:block;font-size:9px;text-align:center;color:#b6a2c2">people</small></strong></div><div class="chart-legend"><?php foreach($departments as $i=>$department):?><div><i style="background:<?=$colors[$i%6]?>"></i><?=e($department['department'])?> <strong style="font-weight:500"><?=(int)$department['total']?></strong></div><?php endforeach;?></div></div></section></div>
<section class="card people-table"><div class="section-head"><h3>Your people</h3><a href="/admin/people.php">View everyone ↗</a></div><?php foreach($people as $person):$parts=explode(' ',$person['full_name']);$initials=substr($parts[0],0,1).substr(end($parts),0,1);?><a class="people-row" href="/admin/people.php?person=<?=(int)$person['id']?>"><div class="avatar" style="background:<?=e(preg_match('/^#[a-fA-F0-9]{6}$/',$person['avatar_color']??'')?$person['avatar_color']:'#b6a2ed')?>"><?=e($initials)?></div><div><strong><?=e($person['full_name'])?></strong><small><?=e($person['job_title']??'Team member')?></small></div><p><?=e($person['department']??'General')?></p><span class="pill"><?=e(ucfirst($person['status']))?></span></a><?php endforeach;?><?php if(!$people):?><div class="empty-state">Add your first team member to get started.</div><?php endif;?></section>
</div><aside class="right-rail">
<section class="card calendar-card"><div class="calendar-title"><span><?=date('F Y')?></span><a href="/employee/leave.php" aria-label="Open leave calendar">▦</a></div><div class="calendar-grid"><?php foreach(['M','T','W','T','F','S','S'] as $day):?><span class="day-name"><?=$day?></span><?php endforeach;for($i=1;$i<$firstDay;$i++):?><span></span><?php endfor;for($i=1;$i<=$monthDays;$i++):?><span class="<?=$i==date('j')?'today':''?>"><?=$i?></span><?php endfor;?></div></section>
<section class="card"><div class="section-head"><h3>Your action center</h3><span>↗</span></div><?php foreach([['Documents to review',$stats['pending_docs'],'/admin/documents.php'],['Timesheets to approve',$stats['pending_timesheets'],'/admin/submitted_timesheets.php'],['Leave requests',$pendingLeave,'/employee/leave.php']] as [$label,$value,$link]):?><a class="people-row" href="<?=e($link)?>"><span style="color:#b7a0d0">◌</span><strong><?=e($label)?></strong><span class="pill" style="background:#f3ecfa;color:#a084bb"><?=$value?></span></a><?php endforeach;?></section>
<section class="card"><div class="section-head"><h3>Recent activity</h3><a href="/admin/audit_log.php">View all</a></div><?php foreach($activities as $activity):?><div class="activity-item"><span class="activity-dot"></span><div><p><?=e(ucwords(str_replace('_',' ',$activity['action'])))?></p><small><?=e(date('M j · H:i',strtotime($activity['created_at'])))?></small></div></div><?php endforeach;?></section>
<section class="rail-promo"><h3>A space for<br>your next big thing.</h3><p>Step inside your digital workspace.</p><a href="/workspace.php" class="btn btn-outline btn-sm">Explore in 3D ↗</a></section>
</aside></div></div></main></div><?php pageFooter();?></body></html>
