<?php
require_once __DIR__.'/layout.php';sendSecurityHeaders();sendNoCacheHeaders();
$signedIn=!empty($_SESSION['user_id']);$staticPreview=defined('APP_STATIC_PREVIEW')&&APP_STATIC_PREVIEW;$destination=$staticPreview?'/preview-dashboard.php':($signedIn?(in_array($_SESSION['role']??'', ['hr_admin','super_admin'],true)?'/admin/dashboard.php':'/employee/dashboard.php'):'/auth/login.php');
pageHead('A new dimension of work');
?>
<body class="reference-landing">
<main class="reference-frame" id="reference-frame">
 <div class="reference-stage">
  <div class="reference-main-art" data-reference-sculpture aria-hidden="true"></div>
  <header class="reference-nav"><a class="reference-brand" href="/" aria-label="CloudFen home">CloudFen<span> / peopleOS</span></a><nav aria-label="Explore the portal"><button type="button" data-view="home" aria-pressed="true">Home</button><button type="button" data-view="how" aria-pressed="false">How it works</button><button type="button" data-view="about" aria-pressed="false">About</button><button type="button" data-view="advantages" aria-pressed="false">Advantages</button></nav><?php if($staticPreview):?><a href="<?=e($destination)?>" class="reference-request">View preview <span>↗</span></a><?php elseif($signedIn):?><a href="<?=e($destination)?>" class="reference-request">Open workspace <span>↗</span></a><?php else:?><button type="button" class="reference-request" id="open-signin" aria-label="Sign in">Sign in <span>↗</span></button><?php endif;?></header>
  <section class="reference-panel reference-home" data-panel="home"><div class="reference-intro"><span>Work is</span><h2>Connected.<br>Human. Simple.</h2></div><div class="reference-floating-card"><span class="reference-card-label">ONE CONNECTED WORKSPACE</span><strong>03</strong><div class="reference-card-ring" aria-hidden="true"></div><p>Employee, HR, and administrator.<br>The right space for every role.</p></div><h1>A new dimension<br>of work.<br>Built around people.</h1></section>
  <section class="reference-panel reference-detail" data-panel="how" hidden><div class="reference-section-title"><span>How it works</span><h2>A clearer path<br>through your workday.</h2></div><div class="reference-steps"><article><span>01</span><h3>Sign in</h3><p>Enter your workspace with the access assigned to your role.</p></article><article><span>02</span><h3>Connect</h3><p>Find your people, assignments, documents, and important updates.</p></article><article><span>03</span><h3>Move forward</h3><p>Track time, request leave, and keep projects moving.</p></article></div></section>
  <section class="reference-panel reference-detail" data-panel="about" hidden><div class="reference-section-title"><span>About</span><h2>Your people.<br>A world of possibilities.</h2></div><div class="reference-steps"><article><span>01</span><h3>People</h3><p>Profiles, an organization directory, and tools for your HR team.</p></article><article><span>02</span><h3>Progress</h3><p>Goals, reviews, project tasks, and meaningful next steps.</p></article><article><span>03</span><h3>Everyday work</h3><p>Attendance, leave, documents, and weekly timesheets together.</p></article></div></section>
  <section class="reference-panel reference-detail" data-panel="advantages" hidden><div class="reference-section-title"><span>Advantages</span><h2>Beautiful on the surface.<br>Connected underneath.</h2></div><div class="reference-steps"><article><span>01</span><h3>Live</h3><p>Analytics connected to your actual workspace data.</p></article><article><span>02</span><h3>Personal</h3><p>Role-based access and employee-scoped private records.</p></article><article><span>03</span><h3>Flexible</h3><p>Pie charts, bar graphs, and project progress in one view.</p></article></div></section>
  <div class="reference-footer"><span>PEOPLE / TIME / PROGRESS</span><a href="<?=e($destination)?>">Explore your workspace ↗</a></div>
 </div>
</main>
<?php if(!$signedIn && !$staticPreview):?>
<dialog class="reference-signin" id="reference-signin"><button type="button" class="reference-close" id="close-signin" aria-label="Close sign-in">×</button><a class="reference-brand" href="/">CloudFen</a><div class="reference-drawer-heading"><span class="eyebrow">YOUR WORKSPACE AWAITS</span><h2>Welcome inside.</h2><p>Sign in to your connected HR workspace.</p></div>
<?php if(defined('APP_DEMO_MODE')&&APP_DEMO_MODE):?><p class="demo-login-note">Fictional demo accounts. Select a role and enter your demo password.</p><div class="demo-role-picker" role="group" aria-label="Choose demo sign-in role"><button type="button" data-email="demo.ava.bennett@example.invalid" aria-pressed="false">Employee</button><button type="button" data-email="demo.hr@example.invalid" aria-pressed="false">HR manager</button><button type="button" data-email="demo.admin@example.invalid" aria-pressed="false">Administrator</button></div><?php endif;?>
<form method="post" action="/auth/login.php" data-loading><input type="hidden" name="csrf_token" value="<?=e(generateCsrfToken())?>"><?=honeypotField()?><div class="form-group"><label for="welcome-email">Email address</label><input id="welcome-email" class="form-control" name="email" type="email" required autocomplete="username" placeholder="you@example.com"></div><div class="form-group"><label for="welcome-password">Password</label><input id="welcome-password" class="form-control" name="password" type="password" required autocomplete="current-password" placeholder="Your password"></div><button type="submit" class="btn btn-primary btn-block">Sign In →</button><a class="reference-forgot" href="/auth/forgot.php">Forgot password?</a></form><p class="reference-drawer-note">Your account determines the data and actions available to you.</p></dialog>
<?php endif;pageFooter();?>
<script src="/assets/js/demo-login.js"></script><script src="/assets/js/reference-home.js?v=<?=filemtime(__DIR__.'/../assets/js/reference-home.js')?>"></script>
</body></html>
