<?php
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../includes/helpers.php';
if(!in_array('--local-demo',$argv,true)){exit("Run with --local-demo against a dedicated demonstration database. All generated accounts are fictional.\n");}
$db=getDB();$db->exec(file_get_contents(__DIR__.'/../config/migration_people.sql'));
$adminId=(int)$db->query("SELECT id FROM users WHERE role='super_admin' ORDER BY id LIMIT 1")->fetchColumn();if(!$adminId)exit("Create a super administrator before loading demo profiles.\n");
$enableLogins=in_array('--enable-logins',$argv,true);
$demoPassword=getenv('DEMO_ACCOUNT_PASSWORD') ?: '';
if($enableLogins && (!defined('APP_DEMO_MODE') || !APP_DEMO_MODE || strlen($demoPassword)<14)) exit("Enable APP_DEMO_MODE and provide a DEMO_ACCOUNT_PASSWORD of at least 14 characters before enabling demo sign-ins.\n");
$people=[['Ava Bennett','Engineering','Frontend Engineer','New York','#b6a2ed'],['Liam Foster','Design','Product Designer','London','#efad9b'],['Sofia Chen','People','People Partner','Singapore','#a6cbb3'],['Noah Williams','Engineering','Engineering Lead','Austin','#a0bfe8'],['Maya Patel','Marketing','Brand Strategist','London','#e7c28c'],['Ethan Brooks','Finance','Finance Analyst','New York','#c4addc'],['Isabella Reed','Design','Design Director','Berlin','#efb0c2'],['Lucas Morgan','Engineering','Backend Engineer','Toronto','#98ccc4'],['Amelia Hayes','Marketing','Growth Lead','Austin','#a6b6e9'],['Oliver Kim','Operations','Operations Manager','Singapore','#d0caa5'],['Zara Collins','People','Recruitment Partner','Remote','#ddb4e4'],['Leo Martinez','Engineering','QA Engineer','Berlin','#a4c7d4']];
$db->beginTransaction();try{
foreach($people as $i=>[$name,$department,$job,$location,$color]){
 $email='demo.'.strtolower(str_replace(' ','.',$name)).'@example.invalid';$q=$db->prepare('SELECT id FROM users WHERE email=?');$q->execute([$email]);$id=$q->fetchColumn();
 if($id&&$enableLogins){$q=$db->prepare('SELECT is_demo FROM workspace_people WHERE user_id=?');$q->execute([$id]);if((int)$q->fetchColumn()!==1)throw new RuntimeException('Reserved demo email belongs to a non-demo account.');}
 if(!$id){$db->prepare("INSERT INTO users(full_name,email,password_hash,role,status,email_verified,employee_type,start_date,date_of_birth,address,emergency_contact,created_at) VALUES(?,?,?,'employee','active',1,'W2',?,'1994-05-12','Fictional demo address',?,?)")->execute([$name,$email,password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT),date('Y-m-d',strtotime('-'.(30+$i*18).' days')),json_encode(['name'=>'Demo contact','phone'=>'2025550100']),date('Y-m-d H:i:s',strtotime('-'.(30+$i*18).' days'))]);$id=(int)$db->lastInsertId();}
 $db->prepare('INSERT INTO workspace_people(user_id,department,job_title,location,is_demo,avatar_color) VALUES(?,?,?,?,1,?) ON DUPLICATE KEY UPDATE department=VALUES(department),job_title=VALUES(job_title),location=VALUES(location),is_demo=1,avatar_color=VALUES(avatar_color)')->execute([$id,$department,$job,$location,$color]);
 if($enableLogins){$db->prepare("UPDATE users SET password_hash=?,failed_logins=0,locked_until=NULL,status='active',email_verified=1,force_password_change=0 WHERE id=?")->execute([password_hash($demoPassword,PASSWORD_DEFAULT),$id]);}
 $q=$db->prepare('SELECT COUNT(*) FROM attendance WHERE user_id=?');$q->execute([$id]);if(!$q->fetchColumn())for($d=0;$d<7;$d++){if(($i+$d)%6===0)continue;$day=date('Y-m-d',strtotime("-$d days"));$db->prepare('INSERT IGNORE INTO attendance(user_id,work_date,clock_in,clock_out) VALUES(?,?,?,?)')->execute([$id,$day,"$day 09:00:00","$day 17:00:00"]);}
 $q=$db->prepare('SELECT COUNT(*) FROM projects WHERE employee_id=?');$q->execute([$id]);if(!$q->fetchColumn())$db->prepare('INSERT INTO projects(employee_id,client_name,project_name,created_by) VALUES(?,?,?,?)')->execute([$id,'Demo Studio',['Platform redesign','Employee experience','Growth strategy'][$i%3],$adminId]);
 $db->prepare("INSERT IGNORE INTO timesheets(user_id,week_start,mon_hours,tue_hours,wed_hours,thu_hours,fri_hours,status,notes,submitted_at) VALUES(?,?,8,8,8,8,8,?,'Fictional demonstration timesheet',NOW())")->execute([$id,date('Y-m-d',strtotime('monday this week')),$i<6?'pending':'approved']);
 if($i<3){$q=$db->prepare("SELECT id FROM leave_requests WHERE user_id=? AND reason='Fictional demo leave request'");$q->execute([$id]);if(!$q->fetchColumn())$db->prepare("INSERT INTO leave_requests(user_id,leave_type,start_date,end_date,reason) VALUES(?,'annual',?,?,'Fictional demo leave request')")->execute([$id,date('Y-m-d',strtotime('+'.(7+$i*3).' days')),date('Y-m-d',strtotime('+'.(9+$i*3).' days'))]);}
 $q=$db->prepare('SELECT COUNT(*) FROM performance_goals WHERE user_id=?');$q->execute([$id]);if(!$q->fetchColumn())$db->prepare('INSERT INTO performance_goals(user_id,title,due_date,progress) VALUES(?,?,?,?)')->execute([$id,'Demo: '.$job.' development plan',date('Y-m-d',strtotime('+60 days')),35+$i*5]);
}
foreach(['Senior Product Designer','Full-stack Engineer','People Operations Partner','Growth Marketing Manager'] as $index=>$job){$q=$db->prepare('SELECT id FROM job_openings WHERE title=?');$q->execute(['Demo: '.$job]);if(!$q->fetchColumn())$db->prepare("INSERT INTO job_openings(title,employment_type,location,description,posted_date,status) VALUES(?,'Full Time',?,?,CURRENT_DATE,'active')")->execute(['Demo: '.$job,['London','Remote','New York','Austin'][$index],'Fictional demonstration opening. Help shape a thoughtful, people-first workplace.']);}
if($enableLogins){foreach([['demo.hr@example.invalid','Demo HR Manager','hr_admin'],['demo.admin@example.invalid','Demo Administrator','super_admin']] as [$email,$name,$role]){
 $q=$db->prepare('SELECT id FROM users WHERE email=?');$q->execute([$email]);$id=$q->fetchColumn();
 if(!$id){$db->prepare("INSERT INTO users(full_name,email,password_hash,role,status,email_verified,date_of_birth,address,emergency_contact) VALUES(?,?,?,?,'active',1,'1990-01-01','Fictional demo address',?)")->execute([$name,$email,password_hash($demoPassword,PASSWORD_DEFAULT),$role,json_encode(['name'=>'Demo contact','phone'=>'2025550100'])]);$id=(int)$db->lastInsertId();}
 else {$q=$db->prepare('SELECT is_demo FROM workspace_people WHERE user_id=?');$q->execute([$id]);if((int)$q->fetchColumn()!==1)throw new RuntimeException('Reserved demo email already belongs to a non-demo account.');$db->prepare("UPDATE users SET password_hash=?,status='active',email_verified=1,failed_logins=0,locked_until=NULL WHERE id=?")->execute([password_hash($demoPassword,PASSWORD_DEFAULT),$id]);}
 $db->prepare("INSERT INTO workspace_people(user_id,department,job_title,location,is_demo,avatar_color) VALUES(?,'People',?,'Demo workspace',1,'#68bcb0') ON DUPLICATE KEY UPDATE is_demo=1")->execute([$id,$role==='hr_admin'?'Demo HR Manager':'Demo Administrator']);
}}
$db->commit();echo "12 fictional demo profiles with sample attendance, projects, goals and 4 demo job openings are ready. Existing real accounts are unchanged.\n";
}catch(Throwable $e){$db->rollBack();throw $e;}
